2018-06-29 11:14:13,438 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2018-06-29 11:14:32,678 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-06-29 11:14:33,058 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/commons.js
2018-06-29 11:14:33,499 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/commons.js
2018-06-29 11:14:58,797 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-06-29 11:48:11,403 [HttpRunnerManager:151] [operation:add_case_data] [INFO]- 的用例添加成功: {'test': {'request': {'method': 'POST', 'url': ''}, 'name': '的'}}
2018-06-29 11:48:48,076 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 13:34:18,047 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/css/css-index.css
2018-07-02 13:34:18,057 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/logo.png
2018-07-02 13:34:18,268 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:18,270 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:18,276 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:18,278 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:18,296 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/bg.jpg
2018-07-02 13:34:18,299 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/loading.GIF
2018-07-02 13:34:18,352 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:18,364 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:18,370 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:18,383 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:18,578 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/favicon.ico
2018-07-02 13:34:21,442 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/css/css-index.css
2018-07-02 13:34:21,445 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:21,449 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/logo.png
2018-07-02 13:34:21,484 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:21,487 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:21,492 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:21,508 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:21,516 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/bg.jpg
2018-07-02 13:34:21,519 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/loading.GIF
2018-07-02 13:34:21,531 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:21,540 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:21,545 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:22,424 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/css/css-index.css
2018-07-02 13:34:22,426 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/logo.png
2018-07-02 13:34:22,429 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:22,465 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:22,466 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:22,468 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:22,480 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:22,483 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/bg.jpg
2018-07-02 13:34:22,490 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/loading.GIF
2018-07-02 13:34:22,498 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:22,506 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:22,509 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:35:30,488 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 13:48:28,352 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 13:53:41,984 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/test_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:/HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:/HttpRunnerManager\ApiManager\views.py", line 379, in test_list
    filter_query = set_filter_session(request)
  File "D:/HttpRunnerManager\ApiManager\utils\common.py", line 439, in set_filter_session
    'belong_project': request.session['project'],
  File "E:\Python35\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'project'
2018-07-02 13:53:49,147 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/test_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:/HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:/HttpRunnerManager\ApiManager\views.py", line 379, in test_list
    filter_query = set_filter_session(request)
  File "D:/HttpRunnerManager\ApiManager\utils\common.py", line 439, in set_filter_session
    'belong_project': request.session['project'],
  File "E:\Python35\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'project'
2018-07-02 13:54:04,117 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 13:54:07,459 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 13:57:09,661 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 13:57:11,824 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:04:39,039 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:04:44,830 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:04:54,650 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/test_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 379, in test_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 432, in set_filter_session
    request.session['module'] = ModuleInfo.objects.get(id=request.POST.get('module')).module_name
  File "E:\Python35\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 394, in get
    clone = self.filter(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1253, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1277, in _add_q
    split_subq=split_subq,
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1215, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1085, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 18, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 68, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "E:\Python35\lib\site-packages\django\db\models\fields\__init__.py", line 947, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
2018-07-02 14:06:02,565 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/config_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 413, in config_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 432, in set_filter_session
    request.session['module'] = ModuleInfo.objects.get(id=request.POST.get('module')).module_name
  File "E:\Python35\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 394, in get
    clone = self.filter(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1253, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1277, in _add_q
    split_subq=split_subq,
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1215, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1085, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 18, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 68, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "E:\Python35\lib\site-packages\django\db\models\fields\__init__.py", line 947, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
2018-07-02 14:24:14,328 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:24:16,921 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:27:17,963 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 323, in project_list
    return render_to_response('project_list.html', manage_info)
  File "E:\Python35\lib\site-packages\django\shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\Python35\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Python35\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Python35\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 176: 'endif', expected 'endblock'. Did you forget to register or load this tag?
2018-07-02 14:27:44,949 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 323, in project_list
    return render_to_response('project_list.html', manage_info)
  File "E:\Python35\lib\site-packages\django\shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\Python35\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Python35\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Python35\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 176: 'endif', expected 'endblock'. Did you forget to register or load this tag?
2018-07-02 14:27:47,983 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 323, in project_list
    return render_to_response('project_list.html', manage_info)
  File "E:\Python35\lib\site-packages\django\shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\Python35\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Python35\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Python35\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 176: 'endif', expected 'endblock'. Did you forget to register or load this tag?
2018-07-02 14:28:16,257 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:28:18,192 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:37:16,138 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 311, in project_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 442, in set_filter_session
    'belong_project': request.session['project'],
  File "E:\Python35\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'project'
2018-07-02 14:37:20,563 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 311, in project_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 442, in set_filter_session
    'belong_project': request.session['project'],
  File "E:\Python35\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'project'
2018-07-02 14:37:24,899 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:37:26,773 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:37:30,837 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/add_case/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 170, in add_case
    msg = case_info_logic(**testcase_info)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 210, in case_info_logic
    test = kwargs.pop('test')
KeyError: 'test'
2018-07-02 14:37:33,775 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/add_case/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 170, in add_case
    msg = case_info_logic(**testcase_info)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 210, in case_info_logic
    test = kwargs.pop('test')
KeyError: 'test'
2018-07-02 14:39:25,603 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:39:27,918 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:43:42,829 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:43:44,932 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:47:52,728 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:47:54,981 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:55:50,890 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:55:53,036 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:57:17,859 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/module_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 345, in module_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 433, in set_filter_session
    request.session['module'] = ModuleInfo.objects.get(id=request.POST.get('module')).module_name
  File "E:\Python35\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 394, in get
    clone = self.filter(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1253, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1277, in _add_q
    split_subq=split_subq,
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1215, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1085, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 18, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 68, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "E:\Python35\lib\site-packages\django\db\models\fields\__init__.py", line 947, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '用例_quant_login_out(登入登出)'
2018-07-02 14:59:50,449 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:59:52,333 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2019-07-24 11:00:02,719 [django.request:228] [log:log_response] [WARNING]- Not Found: /
2019-07-24 11:01:37,104 [HttpRunnerManager:60] [views:login] [INFO]- yetj@wecut.com 登录失败, 请检查用户名或者密码
2019-07-24 11:01:56,005 [HttpRunnerManager:60] [views:login] [INFO]- yetj@wecut.com 登录失败, 请检查用户名或者密码
2019-07-24 11:02:37,449 [HttpRunnerManager:35] [operation:add_register_data] [INFO]- 新增用户：ApiManager.UserInfo.objects
2019-07-24 11:02:51,388 [HttpRunnerManager:55] [views:login] [INFO]- ytj 登录成功
2019-07-24 11:07:00,552 [HttpRunnerManager:62] [operation:add_project_data] [INFO]- 项目添加成功：{'project_name': '装扮少女', 'responsible_name': 'zhulili', 'test_user': 'yetj', 'dev_user': 'zhaoshuai', 'publish_app': 'zhuangban', 'simple_desc': 'game', 'other_desc': '1245'}
2019-07-24 11:07:51,089 [HttpRunnerManager:110] [operation:add_module_data] [INFO]- 模块添加成功：{'module_name': '用户信息', 'test_user': 'yetj', 'simple_desc': '用户相关', 'other_desc': '无', 'belong_project': <ProjectInfo: ProjectInfo object (1)>}
2019-07-24 11:24:53,358 [django.request:228] [log:log_response] [WARNING]- Not Found: /api/
2019-07-24 11:25:27,545 [HttpRunnerManager:55] [views:login] [INFO]- ytj 登录成功
2019-07-24 11:26:37,026 [django.request:228] [log:log_response] [WARNING]- Not Found: /api/
2019-07-24 11:54:19,821 [HttpRunnerManager:154] [operation:add_case_data] [INFO]- 获取token用例添加成功: {'test': {'request': {'url': '/cameraSeries/getToken.php', 'method': 'POST', 'params': {'appId': '10051', 'sign': 'd55351f58f0061a01ca1a8754afa5927', 'ts': '1556416727', 'appversion': '2.0.0', 'osid': '2', 'device': 'bad898e0-182c-49a0-b1bc-6ac4c1ea8f85'}, 'headers': {'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjlONEh1U2NGVHhkN21nd0Z3STV3In0.eyJpc3MiOiJodHRwczpcL1wvYXBpLndlY3V0LmNvbSIsImF1ZCI6Imh0dHBzOlwvXC9hdWRpZW5jZS53ZWN1dC5jb20iLCJqdGkiOiI5TjRIdVNjRlR4ZDdtZ3dGd0k1dyIsImlhdCI6MTU2MzkzODEyMCwibmJmIjoxNTYzOTM4MTIwLCJleHAiOjIxOTQ2NTgxMjAsInVpZCI6IjE2NTQifQ.dPw-t2IikJoVShY-K7BrxTn1nj2SnCHRTRa2afDhUTM'}}, 'name': '获取token'}}
2019-07-24 11:59:04,556 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 获取token用例更新成功: {'test': {'request': {'url': '/cameraSeries/getToken.php', 'method': 'POST', 'params': {'appId': '10051', 'sign': 'd55351f58f0061a01ca1a8754afa5927', 'ts': '1556416727', 'appversion': '2.0.0', 'osid': '2', 'device': 'bad898e0-182c-49a0-b1bc-6ac4c1ea8f85'}, 'headers': {'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjlONEh1U2NGVHhkN21nd0Z3STV3In0.eyJpc3MiOiJodHRwczpcL1wvYXBpLndlY3V0LmNvbSIsImF1ZCI6Imh0dHBzOlwvXC9hdWRpZW5jZS53ZWN1dC5jb20iLCJqdGkiOiI5TjRIdVNjRlR4ZDdtZ3dGd0k1dyIsImlhdCI6MTU2MzkzODEyMCwibmJmIjoxNTYzOTM4MTIwLCJleHAiOjIxOTQ2NTgxMjAsInVpZCI6IjE2NTQifQ.dPw-t2IikJoVShY-K7BrxTn1nj2SnCHRTRa2afDhUTM'}}, 'name': '获取token', 'validate': [{'comparator': 'equals', 'check': '$code', 'expected': '0'}], 'extract': [{'token': 'data.token'}]}}
2019-07-24 12:00:21,371 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 获取token用例更新成功: {'test': {'request': {'url': '/cameraSeries/getToken.php', 'method': 'POST', 'params': {'appId': '10051', 'sign': 'd55351f58f0061a01ca1a8754afa5927', 'ts': '1556416727', 'appversion': '2.0.0', 'osid': '2', 'device': 'bad898e0-182c-49a0-b1bc-6ac4c1ea8f85'}, 'headers': {'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjlONEh1U2NGVHhkN21nd0Z3STV3In0.eyJpc3MiOiJodHRwczpcL1wvYXBpLndlY3V0LmNvbSIsImF1ZCI6Imh0dHBzOlwvXC9hdWRpZW5jZS53ZWN1dC5jb20iLCJqdGkiOiI5TjRIdVNjRlR4ZDdtZ3dGd0k1dyIsImlhdCI6MTU2MzkzODEyMCwibmJmIjoxNTYzOTM4MTIwLCJleHAiOjIxOTQ2NTgxMjAsInVpZCI6IjE2NTQifQ.dPw-t2IikJoVShY-K7BrxTn1nj2SnCHRTRa2afDhUTM'}}, 'name': '获取token', 'validate': [{'comparator': 'equals', 'check': '$code', 'expected': '0'}], 'extract': [{'token': 'content.data.token'}]}}
2019-07-24 12:01:56,129 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 获取token用例更新成功: {'test': {'request': {'url': '/cameraSeries/getToken.php', 'method': 'POST', 'params': {'appId': '10051', 'sign': 'd55351f58f0061a01ca1a8754afa5927', 'ts': '1556416727', 'appversion': '2.0.0', 'osid': '2', 'device': 'bad898e0-182c-49a0-b1bc-6ac4c1ea8f85'}, 'headers': {'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjlONEh1U2NGVHhkN21nd0Z3STV3In0.eyJpc3MiOiJodHRwczpcL1wvYXBpLndlY3V0LmNvbSIsImF1ZCI6Imh0dHBzOlwvXC9hdWRpZW5jZS53ZWN1dC5jb20iLCJqdGkiOiI5TjRIdVNjRlR4ZDdtZ3dGd0k1dyIsImlhdCI6MTU2MzkzODEyMCwibmJmIjoxNTYzOTM4MTIwLCJleHAiOjIxOTQ2NTgxMjAsInVpZCI6IjE2NTQifQ.dPw-t2IikJoVShY-K7BrxTn1nj2SnCHRTRa2afDhUTM'}}, 'name': '获取token', 'validate': [{'comparator': 'equals', 'check': '$code', 'expected': '0'}], 'extract': [{'token': 'content.data.token'}, {'code': 'content.code'}]}}
2019-07-24 12:03:12,104 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 获取token用例更新成功: {'test': {'request': {'url': '/cameraSeries/getToken.php', 'method': 'POST', 'params': {'appId': '10051', 'sign': 'd55351f58f0061a01ca1a8754afa5927', 'ts': '1556416727', 'appversion': '2.0.0', 'osid': '2', 'device': 'bad898e0-182c-49a0-b1bc-6ac4c1ea8f85'}, 'headers': {'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjlONEh1U2NGVHhkN21nd0Z3STV3In0.eyJpc3MiOiJodHRwczpcL1wvYXBpLndlY3V0LmNvbSIsImF1ZCI6Imh0dHBzOlwvXC9hdWRpZW5jZS53ZWN1dC5jb20iLCJqdGkiOiI5TjRIdVNjRlR4ZDdtZ3dGd0k1dyIsImlhdCI6MTU2MzkzODEyMCwibmJmIjoxNTYzOTM4MTIwLCJleHAiOjIxOTQ2NTgxMjAsInVpZCI6IjE2NTQifQ.dPw-t2IikJoVShY-K7BrxTn1nj2SnCHRTRa2afDhUTM'}}, 'name': '获取token', 'validate': [{'comparator': 'equals', 'check': '$msg', 'expected': 'ok'}], 'extract': [{'token': 'content.data.token'}, {'msg': 'content.msg'}]}}
2019-07-24 12:04:29,913 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 获取token用例更新成功: {'test': {'request': {'url': '/cameraSeries/getToken.php', 'method': 'POST', 'params': {'appId': '10051', 'sign': 'd55351f58f0061a01ca1a8754afa5927', 'ts': '1556416727', 'appversion': '2.0.0', 'osid': '2', 'device': 'bad898e0-182c-49a0-b1bc-6ac4c1ea8f85'}, 'headers': {'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjlONEh1U2NGVHhkN21nd0Z3STV3In0.eyJpc3MiOiJodHRwczpcL1wvYXBpLndlY3V0LmNvbSIsImF1ZCI6Imh0dHBzOlwvXC9hdWRpZW5jZS53ZWN1dC5jb20iLCJqdGkiOiI5TjRIdVNjRlR4ZDdtZ3dGd0k1dyIsImlhdCI6MTU2MzkzODEyMCwibmJmIjoxNTYzOTM4MTIwLCJleHAiOjIxOTQ2NTgxMjAsInVpZCI6IjE2NTQifQ.dPw-t2IikJoVShY-K7BrxTn1nj2SnCHRTRa2afDhUTM'}}, 'name': '获取token', 'validate': [{'comparator': 'equals', 'check': '$msg', 'expected': 'ok'}, {'comparator': 'equals', 'check': '$code', 'expected': 0}], 'extract': [{'token': 'content.data.token'}, {'msg': 'content.msg'}, {'code': 'content.code'}]}}
2019-07-24 12:06:00,009 [HttpRunnerManager:89] [views:log_out] [INFO]- ytj退出
2019-07-24 12:06:55,571 [HttpRunnerManager:55] [views:login] [INFO]- ytj 登录成功
2019-07-24 12:29:30,627 [HttpRunnerManager:154] [operation:add_case_data] [INFO]- 查看用户信息用例添加成功: {'test': {'request': {'url': '', 'method': 'POST'}, 'name': '查看用户信息'}}
2019-07-24 12:52:25,217 [HttpRunnerManager:89] [views:log_out] [INFO]- ytj退出
2019-07-24 12:52:31,774 [HttpRunnerManager:55] [views:login] [INFO]- ytj 登录成功
